version: '3.2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - type: bind
        source: ./jenkins_home
        target: /var/jenkins_home
